-- 1. DROP EXISTING TABLES IF NEEDED (OPTIONAL - BE CAREFUL)
-- DROP TABLE IF EXISTS bookings;
-- DROP TABLE IF EXISTS coach_settings;
-- DROP TABLE IF EXISTS availability_rules;

-- 2. CREATE TABLES (IF NOT EXIST)
CREATE TABLE IF NOT EXISTS coach_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  coach_id TEXT NOT NULL UNIQUE, 
  google_calendar_id TEXT,
  email_notifications BOOLEAN DEFAULT true,
  work_start_time TIME DEFAULT '08:00',
  work_end_time TIME DEFAULT '20:00',
  session_duration_minutes INTEGER DEFAULT 60
);

CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  coach_id TEXT NOT NULL,
  client_name TEXT NOT NULL,
  client_email TEXT NOT NULL,
  client_phone TEXT,
  start_time TIMESTAMP WITH TIME ZONE NOT NULL,
  end_time TIMESTAMP WITH TIME ZONE NOT NULL,
  status TEXT DEFAULT 'pending', 
  gcal_event_id TEXT,
  notes TEXT
);

-- 3. ENABLE RLS (IMPORTANT: Supabase often enables it by default on new tables)
ALTER TABLE coach_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;

-- 4. CREATE PERMISSIVE POLICIES (Fixes "Permission Denied" errors)
-- Allows ANYONE (anon key) to read/write. 
-- For production with Auth, you would change this.

-- coach_settings
CREATE POLICY "Public Read Settings" ON coach_settings FOR SELECT USING (true);
CREATE POLICY "Public Insert/Update Settings" ON coach_settings FOR ALL USING (true);

-- bookings
CREATE POLICY "Public Read Bookings" ON bookings FOR SELECT USING (true);
CREATE POLICY "Public Insert Bookings" ON bookings FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Bookings" ON bookings FOR UPDATE USING (true);
