
/**
 * Boxing24 News Automator Script
 * 
 * INSTRUCTIONS FOR YOUR GEMINI AGENT:
 * 1. Ensure you have the Supabase URL and Key (Service Role Key recommended for writing, or Anon Key with RLS).
 * 2. Run this function with the news data generated.
 */

/*
Example JSON format your Gemini should generate:
{
  "title": "Title of the News",
  "slug": "unique-slug-for-url",
  "excerpt": "Short summary...",
  "content": "<p>Full HTML content...</p>",
  "category": "WORLD",
  "image_url": "https://example.com/image.jpg",
  "author": "AI Reporter"
}
*/

// Installation: npm install @supabase/supabase-js

const { createClient } = require('@supabase/supabase-js');

// REPLACE THESE WITH YOUR PROJECT DETAILS
const SUPABASE_URL = 'YOUR_SUPABASE_URL';
const SUPABASE_KEY = 'YOUR_SUPABASE_SERVICE_ROLE_KEY'; // Use Service Role Key to bypass RLS policies if needed for writing

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

async function postNews(newsData) {
    console.log(`Posting news: ${newsData.title}...`);

    // Add timestamp if not provided
    const payload = {
        ...newsData,
        published_at: newsData.published_at || new Date().toISOString(),
        is_published: true
    };

    const { data, error } = await supabase
        .from('news')
        .insert([payload])
        .select();

    if (error) {
        console.error('Error uploading news:', error);
        return false;
    }

    console.log('Success! News ID:', data[0].id);
    return true;
}

// Example Usage Loop for Gemini
const newArticles = [
    {
        title: "Gemini Raport 1",
        slug: "gemini-raport-1",
        excerpt: "Automated report from AI.",
        content: "<p>Content generated by Gemini...</p>",
        category: "AI NEWS",
        image_url: "https://via.placeholder.com/800x400",
        author: "Gemini Agent"
    }
];

// Uncomment to run:
// newArticles.forEach(article => postNews(article));
