-- Migration V3: Training Plans & Coach Slugs

-- 1. Add coach_slug to profiles to link Auth UUID to 'wojciech-rewczuk' etc.
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS coach_slug TEXT;

-- 2. Training Plans Library (Dynamic)
CREATE TABLE IF NOT EXISTS training_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  creator_id UUID, -- Coach who created it
  title TEXT NOT NULL,
  subtitle TEXT,
  description TEXT,
  level TEXT, -- Basic, Pro, Elite
  duration TEXT, -- e.g. "8 Tygodni"
  schedule JSONB DEFAULT '[]'::jsonb, -- The full JSON structure of week/units
  is_public BOOLEAN DEFAULT false
);

-- 3. Policy (Optional, for now handled by API logic)
-- GRANT ALL ON training_plans TO service_role;
