-- Migration V2: Messaging, User Plans, Sessions, and App Settings

-- 1. MESSAGES TABLE
CREATE TABLE IF NOT EXISTS messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  sender_id UUID NOT NULL, -- References auth.users.id
  receiver_id UUID NOT NULL, -- References auth.users.id or specific coach ID string if mixed system (ideally UUID)
  content TEXT NOT NULL,
  read BOOLEAN DEFAULT false
);

-- 2. USER PLANS (Active plans for clients)
CREATE TABLE IF NOT EXISTS user_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID NOT NULL, -- References auth.users.id
  plan_id TEXT NOT NULL, -- String ID from plansLibrary (e.g. 'fighter-path')
  active BOOLEAN DEFAULT true,
  progress JSONB DEFAULT '{}'::jsonb, -- e.g. { "completed_units": ["u1", "u2"], "current_unit": "u3" }
  UNIQUE(user_id, plan_id)
);

-- 3. USER SESSIONS (History of workouts)
CREATE TABLE IF NOT EXISTS user_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  user_id UUID NOT NULL,
  date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  title TEXT, -- e.g. "Trening Bokserski #4"
  stats JSONB DEFAULT '{}'::jsonb, -- e.g. { "strength": 5, "wellness": { "energy": 8 } }
  xp_earned INTEGER DEFAULT 100
);

-- 4. APP SETTINGS (Admin Config)
CREATE TABLE IF NOT EXISTS app_settings (
  key TEXT PRIMARY KEY, -- e.g. 'seo_meta', 'global_alert'
  value JSONB NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Initial SEO Config
INSERT INTO app_settings (key, value) VALUES 
('seo_meta', '{"title": "Boxing24 - Elite Performance", "description": "System treningowy dla zawodowców."}'::jsonb)
ON CONFLICT (key) DO NOTHING;
