-- Create a table for News
CREATE TABLE news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  lead TEXT, -- summary/excerpt
  content TEXT, -- HTML or Markdown
  category TEXT DEFAULT 'Boks Zawodowy', -- Boks Olimpijski, Zawodowy, Wrocław, Nauka, Psychologia
  image_url TEXT,
  author_name TEXT DEFAULT 'Redakcja',
  is_breaking BOOLEAN DEFAULT false,
  source_link TEXT
);

-- RLS (Row Level Security)
-- ALTER TABLE news ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Enable read access for all users" ON news FOR SELECT USING (true);
-- CREATE POLICY "Enable all access for authenticated users" ON news FOR ALL USING (auth.role() = 'authenticated');
