-- Create a table for Coach Settings (calendar sync, defaults)
CREATE TABLE coach_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  coach_id TEXT NOT NULL UNIQUE, -- matches the 'id' string in frontend data (e.g. 'wojciech-rewczuk')
  google_calendar_id TEXT, -- ID of the GCal to sync with
  email_notifications BOOLEAN DEFAULT true,
  work_start_time TIME DEFAULT '08:00',
  work_end_time TIME DEFAULT '20:00',
  session_duration_minutes INTEGER DEFAULT 60
);

-- Create a table for Availability Rules (overrides, breaks, specific days)
-- If no rule exists for a day, fallback to coach_settings default or general hardcoded defaults.
CREATE TABLE availability_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  coach_id TEXT NOT NULL,
  day_of_week INTEGER, -- 0=Sunday, 1=Monday, etc. (NULL if specific date)
  specific_date DATE, -- NULL if recurring weekly rule
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  is_available BOOLEAN DEFAULT true, -- set false to block a day/time
  reason TEXT -- e.g. "Urlop", "Przerwa obiadowa"
);

-- Create a table for Bookings
CREATE TABLE bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  coach_id TEXT NOT NULL,
  client_name TEXT NOT NULL,
  client_email TEXT NOT NULL,
  client_phone TEXT,
  start_time TIMESTAMP WITH TIME ZONE NOT NULL,
  end_time TIMESTAMP WITH TIME ZONE NOT NULL,
  status TEXT DEFAULT 'pending', -- pending, confirmed, cancelled, completed
  gcal_event_id TEXT, -- to link with Google Calendar event
  notes TEXT
);

-- RLS (Row Level Security) - ENABLE IF YOU HAVE AUTH setup
-- For now, we allow public read/write or you can restrict client-side.
-- ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Enable read access for all users" ON bookings FOR SELECT USING (true);
-- CREATE POLICY "Enable insert for all users" ON bookings FOR INSERT WITH CHECK (true);
